# Generated by Django 2.1 on 2020-05-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table=None,
        ),
    ]
