# Generated by Django 2.1 on 2020-05-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200531_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
