# Generated by Django 2.0 on 2020-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='level',
            field=models.CharField(default='普通用户', max_length=20, verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='playlist',
            field=models.TextField(default='', verbose_name='歌曲列表'),
        ),
    ]
